import { Inter } from "next/font/google";
import "./globals.css";
import "@fontsource/roboto";
import SettingAndFilterOptionsProvider from "../providers/SettingAndFilterOptionsProvider";
import NavSelectLinkProvider from "../providers/NavSelectLinkProvider";
import DataProvider from "../providers/DataProvider.js";
import TenstackProvider from "@/providers/TenstackProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import ReduxPersistProvider from "@/providers/ReduxPersistProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<TenstackProvider>
					{/* <SettingAndFilterOptionsProvider>
            <NavSelectLinkProvider>
              <DataProvider>{children}</DataProvider>
            </NavSelectLinkProvider>
          </SettingAndFilterOptionsProvider> */}
					<ReduxProvider>
						<ReduxPersistProvider>{children}</ReduxPersistProvider>
					</ReduxProvider>
				</TenstackProvider>
			</body>
		</html>
	);
}
